version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - test-db:/var/lib/mysql
      - ./test-db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  test-db:
    driver: local
