packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all apps in direct subdirs of packages/
  - 'apps/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
